// @license
// Copyright (c) 2025 Rljson
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import type { UcFacts } from './usecase-facts.ts';
import { num } from './usecase-svg-kit.ts';

/**
 * Writes an image line. rljson.github.io replaces it by the inlined SVG.
 * @param file - The file name in doc/img
 * @param alt - The alternative text
 */
const img = (file: string, alt: string) => `![${alt}](img/${file})`;

/**
 * Writes the use case page in Markdown, for readers without a technical
 * background. Names and numbers come from the generated world.
 * @param f - The facts
 */
export const usecaseText = (f: UcFacts): string => {
  const m = f.manufacturer;
  const c = f.car;
  const shop = f.workshops.find((w) => w.name === c.workshop)!;
  const [first, second] = f.catalogs;
  const r = f.revision;
  const smallest = f.sizes[0];
  const largest = f.sizes[f.sizes.length - 1];
  const assemblies = f.parts.children.map((p) => p.name.toLowerCase());
  const chain: string[] = [];
  for (let p = f.parts.children[0]; p; p = p.children[0]) chain.push(p.name);

  return `<!--
@license
Copyright (c) 2025 Rljson

Use of this source code is governed by terms that can be
found in the LICENSE file in the root of this package.
-->

<!-- Generated by scripts/usecase/build-usecase.ts. Do not edit. -->

# The car world: what Edge generates and why

Edge invents a small world of cars: manufacturers, their catalogs, the
cars in them, and everything that belongs to a car. This page explains
that world step by step. All names and numbers on this page come from a
real run of Edge.

## Know why we need invented data

Imagine a team that builds an app for car data. The app shows catalogs,
compares prices, finds a workshop and opens a 3D model of a car. Before
real customers put their data into the app, the team wants to try it out.

For that the team needs data that looks real:

- a handful of cars to check quickly whether a screen works
- millions of cars to see whether the app stays fast
- the same cars on every computer, so everybody sees the same result

Collecting real data is slow, and real data is often secret. So Edge
invents it. The world is made up, but it feels real: well-known car
names, plausible prices, workshops with owners and addresses, and parts
down to the last screw.

## See the whole world at a glance

${img('usecase-overview.svg', 'The car world at a glance')}

The world starts with a manufacturer, here ${m.name}. The manufacturer
publishes a catalog for each model year. A catalog lists cars. Each car
comes with five things: a price, a brand and model, a workshop, its parts
and a 3D model.

The next sections follow one car through this world: the ${c.model},
car no. ${c.number} of the catalog ${first.year}.

## Start at the manufacturer

${img('usecase-manufacturer.svg', 'A manufacturer and its catalogs')}

${m.name} was founded in ${m.founded}. Its headquarters is at
${m.headquarters}. Each year it publishes a new catalog: the catalog
${first.year} has ${first.cars.length} cars, the catalog ${second.year} has
${second.cars.length}.

## Look at one car

${img('usecase-car.svg', `One car: the ${c.model}`)}

The ${c.model} costs ${num(c.price)} ${c.currency}. It is a ${c.bodyType}
with ${c.powerKw} kW that runs on ${c.fuel}.

The workshop ${shop.name} in ${shop.city} services the car. It belongs to
${shop.owner} and offers ${shop.services.join(', ')}. Several cars share
one workshop, just like in real life.

## Take the car apart

${img('usecase-parts.svg', 'From the car down to the screws')}

A car is built from assemblies, like the ${assemblies.join(' and the ')}.
Each assembly contains components, each component contains parts, and the
parts are held together by screws, nuts and washers. Follow one branch:
${chain.join(' → ')}.

This list of parts is called the bill of materials. Factories, workshops
and shops all work with it.

## Look at the 3D model

${img('usecase-cad.svg', 'The 3D model of a car')}

Every car also has a 3D model, so an app can show it on the screen. The
model is a tree: groups hold other pieces, and shapes are the pieces you
can see, each made of a material.

## Turn to the next year

${img('usecase-revision.svg', `A new catalog for ${r.to}`)}

A new year brings a new catalog. Most cars stay the same.
${r.added.map((a) => `The ${a.model} (no. ${a.number}) is new.`).join(' ')}
${r.changed.map((x) => `The ${x.after.model} now costs ${num(x.after.price)} instead of ${num(x.before.price)} ${x.after.currency}.`).join(' ')}

Edge stores only what changed. The rest is taken over from the year
before, which keeps the data small and shows exactly what is new.

## Choose the size

${img('usecase-sizes.svg', 'From a handful of cars to millions')}

The same world comes in ${f.sizes.length} sizes, from ${num(smallest.cars)}
cars to ${num(largest.cars)} cars. The team picks the size that fits the
test: a tiny world for a quick check, a huge one for a load test. The same
settings always give the same cars, on every computer.

## Note on names

All data on this page is invented: prices, addresses, people, workshops
and parts. Brand and model names only make the example easier to follow.
They belong to their owners. Edge and Rljson have no connection to any car
manufacturer.

## Read on

- The section »Generate Rljson« on [rljson.github.io](https://rljson.github.io)
  shows step by step how to generate and read this world in code
- The [README of Edge](https://github.com/rljson/edge#readme) lists the settings and the tables of the world
`;
};
