// @license
// Copyright (c) 2025 Rljson
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import type { UcFacts } from './usecase-facts.ts';
import { num } from './usecase-svg-kit.ts';

/**
 * Writes an image line. rljson.github.io replaces it by the inlined SVG.
 * @param file - The file name in doc/img
 * @param alt - The alternative text
 */
const img = (file: string, alt: string) => `![${alt}](img/${file})`;

/**
 * Writes the use case page in Markdown, for readers without a technical
 * background. Names and numbers come from the generated world.
 * @param f - The facts
 */
export const usecaseText = (f: UcFacts): string => {
  const m = f.manufacturer;
  const c = f.car;
  const shop = f.workshops.find((w) => w.name === c.workshop)!;
  const [first, second] = f.catalogs;
  const r = f.revision;
  const smallest = f.sizes[0];
  const largest = f.sizes[f.sizes.length - 1];
  const assemblies = f.parts.children.map((p) => p.name.toLowerCase());
  const chain: string[] = [];
  for (let p = f.parts.children[0]; p; p = p.children[0]) chain.push(p.name);

  return `<!--
@license
Copyright (c) 2025 Rljson

Use of this source code is governed by terms that can be
found in the LICENSE file in the root of this package.
-->

<!-- Generated by scripts/usecase/build-usecase.ts. Do not edit. -->

# The World of Cars

The examples of Rljson use one invented world: car manufacturers, their
catalogs and cars. This page shows that world.

${img('usecase-overview.svg', 'The World of Cars at a glance')}

## Generated Data

The world starts with a manufacturer, here ${m.name}. The manufacturer
publishes a catalog for each model year. A catalog lists cars. Each car
comes with five things: a price, a brand and model, a workshop, its parts
and a 3D model.

## Manufacturer & Catalogs

${img('usecase-manufacturer.svg', 'A manufacturer and its catalogs')}

${m.name} was founded in ${m.founded}. Its headquarters is at
${m.headquarters}. Each year it publishes a new catalog: the catalog
${first.year} has ${first.cars.length} cars, the catalog ${second.year} has
${second.cars.length}.

## Car

${img('usecase-car.svg', `One car: the ${c.model}`)}

The ${c.model} is a ${c.bodyType} for ${num(c.price)} ${c.currency}. The
workshop ${shop.name} in ${shop.city} services it.

## Parts of a car

${img('usecase-parts.svg', 'From the car down to the screws')}

A car is built from assemblies, like the ${assemblies.join(' and the ')}.
Each assembly contains components, each component contains parts, and the
parts are held together by screws, nuts and washers. Follow one branch:
${chain.join(' → ')}.

This list of parts is called the bill of materials. Factories, workshops
and shops all work with it.

## 3D Model of a car

${img('usecase-cad.svg', 'The 3D model of a car')}

Every car also has a 3D model, so an app can show it on the screen. The
model is a tree: groups hold other pieces, and shapes are the pieces you
can see, each made of a material.

## Catalog updates

${img('usecase-revision.svg', `A new catalog for ${r.to}`)}

Each year brings a new catalog. Rljson stores only what changed, here
${r.added.length} new car${r.added.length === 1 ? '' : 's'} and ${r.changed.length} new price${r.changed.length === 1 ? '' : 's'}; the rest is taken over from the year before.

## Size of generated data

${img('usecase-sizes.svg', 'From a handful of cars to millions')}

The same world comes in ${f.sizes.length} sizes, from ${num(smallest.cars)}
cars to ${num(largest.cars)} cars. The team picks the size that fits the
test: a tiny world for a quick check, a huge one for a load test. The same
settings always give the same cars, on every computer.

<sub class="uc-note">Everything on this page is invented: brands, models, companies,
people, workshops, prices and parts. Only countries and cities are real.
Any similarity to real names is coincidental.</sub>
`;
};
